import type { Metadata } from "next";
import Navbar from '@/layout/landingLayout/Navbar'
import Footer from '@/layout/landingLayout/Footer'



export const metadata: Metadata = {
  title: "Landing layout",
  description: "Generated by skillswap",
};

export default function LandingLayout({ children }: LayoutProps<"/">) {
  return (
    <>
    <Navbar />
    {children}
    <Footer />

    </>
    
  );
}
