import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import ReduxProvider from "@/services/helper/provider/ReduxProvider";
import QueryProvider from "@/services/helper/provider/QueryProvider";

const plusJakarta = Plus_Jakarta_Sans({
  variable: "--font-plus-jakarta",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${plusJakarta.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
         <Toaster richColors position="top-right" closeButton/>
         <QueryProvider>
          <ReduxProvider>
          {children}
         </ReduxProvider>
         </QueryProvider>
         
        
        </body>
    </html>
  );
}
