import type { Metadata } from "next";
import Sidebar from '@/layout/userLayout/Sidebar'
import Navbar from '@/layout/userLayout/Navbar'




export const metadata: Metadata = {
  title: "User layout",
  description: "Generated by skillswap",
};

export default function UserLayout({ children }: LayoutProps<"/">) {
  return (
    <>
    <div className="flex flex-col w-full">
        <div className="w-full">
          <Navbar />
        </div>

        <div className="flex flex-row w-full">
          <div className="w-[15%]">
            <Sidebar />
          </div>
          <div className="w-[80%]">
            {children}
          </div>
        </div>
      </div>

    </>
    
  );
}
