import type { Metadata } from "next";
import Sidebar from '@/layout/adminLayout/Sidebar'
import Navbar from '@/layout/adminLayout/Navbar'




export const metadata: Metadata = {
  title: "Admin layout",
  description: "Generated by skillswap",
};

export default function AdminLayout({ children }: LayoutProps<"/">) {
  return (
    <>
     <div className="w-full flex flex-row ">
        <div className="w-[20%]">
          <Sidebar />
        </div>
        <div className="flex flex-col w-[80%]">
          <div>
            <Navbar />
          </div>
          <div>
            {children}
          </div>
        </div>
      </div>

    </>
    
  );
}
